dist: trusty
language: go
go_import_path: github.com/yuyang0/mit-6.824
sudo: false

go:
  - 1.7.x

env:
  - LAB2_TEST_NAME=InitialElection
  - LAB2_TEST_NAME=ReElection
  - LAB2_TEST_NAME=BasicAgree
  - LAB2_TEST_NAME=FailAgree
  - LAB2_TEST_NAME=FailNoAgree
  - LAB2_TEST_NAME=ConcurrentStarts
  - LAB2_TEST_NAME=Rejoin
  - LAB2_TEST_NAME=Backup
  - LAB2_TEST_NAME=Count
  - LAB2_TEST_NAME=Persist1
  - LAB2_TEST_NAME=Persist2
  - LAB2_TEST_NAME=Persist3
  - LAB2_TEST_NAME=Figure8$
  - LAB2_TEST_NAME=UnreliableAgree
  - LAB2_TEST_NAME=Figure8Unreliable
  - LAB2_TEST_NAME=ReliableChurn
  - LAB2_TEST_NAME=UnreliableChurn

  - LAB3_TEST_NAME=TestBasic
  - LAB3_TEST_NAME=TestConcurrent


script:
 # - src/mapreduce/test.sh 5
 - src/raft/test.sh $LAB2_TEST_NAME 80
 - src/kvraft/test.sh $LAB3_TEST_NAME 100
