dist: trusty
language: go
go_import_path: github.com/yuyang0/mit-6.824
sudo: false

go:
  - 1.7.x

env:
  - TEST_NAME="lab2 InitialElection"
  - TEST_NAME="lab2 ReElection"
  - TEST_NAME="lab2 BasicAgree"
  - TEST_NAME="lab2 FailAgree"
  - TEST_NAME="lab2 FailNoAgree"
  - TEST_NAME="lab2 ConcurrentStarts"
  - TEST_NAME="lab2 Rejoin"
  - TEST_NAME="lab2 Backup"
  - TEST_NAME="lab2 Count"
  - TEST_NAME="lab2 Persist1"
  - TEST_NAME="lab2 Persist2"
  - TEST_NAME="lab2 Persist3"
  - TEST_NAME="lab2 Figure8$ 80"
  - TEST_NAME="lab2 UnreliableAgree"
  - TEST_NAME="lab2 Figure8Unreliable 80"
  - TEST_NAME="lab2 ReliableChurn"
  - TEST_NAME="lab2 UnreliableChurn"

  - TEST_NAME="lab3 TestBasic"
  - TEST_NAME="lab3 TestConcurrent"
  - TEST_NAME="lab3 TestUnreliable$"
  - TEST_NAME="lab3 TestUnreliableOneKey$"
  - TEST_NAME="lab3 TestOnePartition$"
  - TEST_NAME="lab3 TestManyPartitionsOneClient     50"
  - TEST_NAME="lab3 TestManyPartitionsManyClients   50"
  - TEST_NAME="lab3 TestPersistOneClient            50"
  - TEST_NAME="lab3 TestPersistConcurrent           50"
  - TEST_NAME="lab3 TestPersistConcurrentUnreliable 50"
  - TEST_NAME="lab3 TestPersistPartition            50"
  - TEST_NAME="lab3 TestPersistPartitionUnreliable  50"
  # - TEST_NAME="lab3 TestSnapshotRPC"
  # - TEST_NAME="lab3 TestSnapshotRecover"
  # - TEST_NAME="lab3 TestSnapshotRecoverManyClients"
  # - TEST_NAME="lab3 TestSnapshotUnreliable"
  # - TEST_NAME="lab3 TestSnapshotUnreliableRecover"
  # - TEST_NAME="lab3 TestSnapshotUnreliableRecoverConcurrentPartition"


script:
 - ./test.sh $TEST_NAME 100

notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: always
    on_failure: always

branches:
  only:
  - master
